### ISSUE TITLE
NotImplementedError: Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by matthew-mcallister** [galatolofederico/vanilla-llama#2]
Maybe I'm clueless, but trying to run inference results in this error:
```
NotImplementedError: Cannot copy out of meta tensor; no data!
```
All converted model files were found, so not sure what's wrong.

**Comment by galatolofederico** [comment]
That's weird. Which GPU do you have? Which CUDA version? Is CUDA installed correctly? `torch.cuda.is_avaialble()` is `True`?

**Comment by randaller** [comment]
Same here, 3070ti, CUDA 11.7, installed correctly, another projects works well with CUDA.

**Comment by galatolofederico** [comment]
I confirm that it is working fine on my machine

```
python convert.py --llama-path ~/federico/llama-weights/LLaMA --model 7B --output-path ~/federico/llama-vanilla
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:06<00:00,  6.91s/it]

python example.py --llama-path ~/federico/llama-vanilla/ --model 7B
Loaded model 7B in 10.48 seconds
['Chat:\nHuman: Hi i am an human\nAI: Hi i am an AI\n']
Inference took 2.71 seconds
```

Lets check the checksum of the converted weights just to be sure. Lets check the 7B version

```
sha256sum 7B/state_dict.pth
f074c39dc9d0988ae5f268acaad41008bab195e9ebf67f7e4182f2b476fb58c4  7B/state_dict.pth
sha256sum 7B/params.json 
14f4c7c7bd98d4d155570f8f30407437e064c3cfc25ec36ed144dc011198bf0d  7B/params.json
```

And also lets check the environment.

```
pip freeze
accelerate==0.17.0
anyio==3.6.2
click==8.1.3
fastapi==0.94.0
h11==0.14.0
httptools==0.5.0
idna==3.4
numpy==1.24.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
packaging==23.0
psutil==5.9.4
pydantic==1.10.6
python-dotenv==1.0.0
PyYAML==6.0
sentencepiece==0.1.97
sniffio==1.3.0
starlette==0.26.0.post1
torch==1.13.1
tqdm==4.65.0
typing-extensions==4.5.0
uvicorn==0.21.0
uvloop==0.17.0
watchfiles==0.18.1
websockets==10.4
```

**Comment by randaller** [comment]
@galatolofederico I am on Windows machine.

```
accelerate==0.17.0
brotlipy==0.7.0
certifi @ file:///C:/b/abs_85o_6fm0se/croot/certifi_1671487778835/work/certifi
cffi @ file:///C:/b/abs_49n3v2hyhr/croot/cffi_1670423218144/work
charset-normalizer @ file:///tmp/build/80754af9/charset-normalizer_1630003229654/work
colorama==0.4.6
cryptography @ file:///C:/b/abs_8ecplyc3n2/croot/cryptography_1677533105000/work
fairscale==0.4.13
fire==0.5.0
flit_core @ file:///opt/conda/conda-bld/flit-core_1644941570762/work/source/flit_core
idna @ file:///C:/b/abs_bdhbebrioa/croot/idna_1666125572046/work
mkl-fft==1.3.1
mkl-random @ file:///C:/ci_310/mkl_random_1643050563308/work
mkl-service==2.4.0
numpy @ file:///C:/b/abs_datssh7cer/croot/numpy_and_numpy_base_1672336199388/work
packaging==23.0
Pillow==9.4.0
psutil==5.9.4
pyarrow==11.0.0
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pyOpenSSL @ file:///C:/b/abs_552w85x1jz/croot/pyopenssl_1677607703691/work
PySocks @ file:///C:/ci_310/pysocks_1642089375450/work
PyYAML==6.0
requests @ file:///C:/ci/requests_1657735340829/work
sentencepiece==0.1.97
six @ file:///tmp/build/80754af9/six_1644875935023/work
termcolor==2.2.0
torch==1.13.1
torchaudio==0.13.1
torchvision==0.14.1
tqdm==4.65.0
typing_extensions @ file:///C:/b/abs_89eui86zuq/croot/typing_extensions_1669923792806/work
urllib3 @ file:///C:/b/abs_9bcwxczrvm/croot/urllib3_1673575521331/work
win-inet-pton @ file:///C:/ci_310/win_inet_pton_1642658466512/work
wincertstore==0.2
```

**Comment by galatolofederico** [comment]
@randaller i dont have a windows machine on hand to test it. Your env looks fine.
I  guess this issue is related to accelerate and the "meta" device ([related issue](https://github.com/lkwq007/stablediffusion-infinity/issues/156)). If you have only 1 GPU you can try loading the model without accelerate

**Comment by galatolofederico** [comment]
Try to do something like this

```python
        state_dict = os.path.join(llama_path, model, "state_dict.pth")
        params_file = os.path.join(llama_path, model, "params.json")
        tokenizer_path = os.path.join(llama_path, "tokenizer.model")

        assert os.path.exists(os.path.join(llama_path, model)), f"Model {model} does not exist"
        assert os.path.exists(state_dict), f"Model {model} does not exist"
        assert os.path.exists(params_file), f"Model {model} does not exist"
        assert os.path.exists(tokenizer_path), f"Missing tokenizer in {llama_path}"

        with open(params_file, "r") as f:
            params = json.load(f)

        model_args = dict(
            max_seq_len=2048,
            max_batch_size=1,
            **params
        )
        model_args.update(kwargs)
        model_args = ModelArgs(**model_args)

        self.tokenizer = Tokenizer(model_path=tokenizer_path)
        model_args.vocab_size = self.tokenizer.n_words

        torch.set_default_tensor_type(torch.HalfTensor)
        model = Transformer(model_args)
        torch.set_default_tensor_type(torch.FloatTensor)

        self.model.load_state_dict(torch.load(state_dict))

        self.generator = LLaMA(self.model, self.tokenizer)
```

**Comment by randaller** [comment]
@galatolofederico that's what I'm actually doing in my repo and torch.load() works perfectly; the idea was to try to offload with accelerate library to get the balanced offload of layers between gpu and cpu.

**Comment by matthew-mcallister** [comment]
> That's weird. Which GPU do you have? Which CUDA version? Is CUDA installed correctly? `torch.cuda.is_avaialble()` is `True`?

`torch.cuda.is_available()` is `True`. Still failing.

**Comment by matthew-mcallister** [comment]
> Try to do something like this

I copied your code and it fails with a different error:

```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper__index_select)
```

**Comment by galatolofederico** [comment]
The issue seems related to accelerate, can you try loading a different model from hf hub using it?

**Comment by lc222** [comment]
I meet a similar issue.
My model files have 8 part bin, I can load the model correctly for inference because it need 10G GPU, so i can load it directly;

But I want finetune it, so that i must load it with deepspeed on multi-gpu, the i got this error.

`
tokenizer = AutoTokenizer.from_pretrained("./chatglm-6b", trust_remote_code=True)
training_args = TrainingArguments(output_dir='./results', num_train_epochs=4, logging_steps=100, save_strategy=IntervalStrategy.NO,
                                  per_device_train_batch_size=16, per_device_eval_batch_size=16, warmup_steps=100,
                                  weight_decay=0.01, logging_dir='./logs', fp16=True, deepspeed='./ds_config_gpt.json')
model = AutoModel.from_pretrained("./chatglm-6b", trust_remote_code=True).half().cuda()
` 

Same code work well when not use deepspeed

**Comment by galatolofederico** [comment]
@lc222 that code is for the huggingface transformers version of llama. I am closing this issue since it is a problem of accelerate in wsl

**Comment by zhogu** [comment]
I also encounter this problem when calling 65B model in ubuntu machine(A100 80G): 
```
NotImplementedError: Cannot copy out of meta tensor; no data!
```

7B, 13B, 30B are all problemless. They can be loaded into GPU. Converted 65B model is too large to totally loaded into A100.

The following are logs. It seems like a problem of accelerate.  Any idea to fix it?

```
python example.py --llama-path /scratch/llama/models/65B_vanilla/ --model 65B || date
*********************** device_map {'tok_embeddings': 0, 'layers.0': 0, 'layers.1': 0, 'layers.2': 0, 'layers.3': 0, 'layers.4': 0, 'layers.5': 0, 'layers.6': 0, 'layers.7': 0, 'layers.8': 0, 'layers.9': 0, 'layers.10': 0, 'layers.11': 0, 'layers.12': 0, 'layers.13': 0, 'layers.14': 0, 'layers.15': 0, 'layers.16': 0, 'layers.17': 0, 'layers.18': 0, 'layers.19': 0, 'layers.20': 0, 'layers.21': 0, 'layers.22': 0, 'layers.23': 0, 'layers.24': 0, 'layers.25': 0, 'layers.26': 0, 'layers.27': 0, 'layers.28': 0, 'layers.29': 0, 'layers.30': 0, 'layers.31': 0, 'layers.32': 0, 'layers.33': 0, 'layers.34': 0, 'layers.35': 0, 'layers.36': 0, 'layers.37': 0, 'layers.38': 0, 'layers.39': 0, 'layers.40': 0, 'layers.41': 0, 'layers.42': 0, 'layers.43': 'cpu', 'layers.44': 'cpu', 'layers.45': 'cpu', 'layers.46': 'cpu', 'layers.47': 'cpu', 'layers.48': 'cpu', 'layers.49': 'cpu', 'layers.50': 'cpu', 'layers.51': 'cpu', 'layers.52': 'cpu', 'layers.53': 'cpu', 'layers.54': 'cpu', 'layers.55': 'cpu', 'layers.56': 'cpu', 'layers.57': 'cpu', 'layers.58': 'cpu', 'layers.59': 'cpu', 'layers.60': 'cpu', 'layers.61': 'cpu', 'layers.62': 'cpu', 'layers.63': 'cpu', 'layers.64': 'cpu', 'layers.65': 'cpu', 'layers.66': 'cpu', 'layers.67': 'cpu', 'layers.68': 'cpu', 'layers.69': 'cpu', 'layers.70': 'cpu', 'layers.71': 'cpu', 'layers.72': 'cpu', 'layers.73': 'cpu', 'layers.74': 'cpu', 'layers.75': 'cpu', 'layers.76': 'cpu', 'layers.77': 'cpu', 'layers.78': 'cpu', 'layers.79': 'cpu', 'norm': 'cpu', 'output': 'cpu'}

Loaded model 65B in 284.80 seconds

0 cuda:0
1 cuda:0
2 cuda:0
3 cuda:0
4 cuda:0
5 cuda:0
6 cuda:0
7 cuda:0
8 cuda:0
9 cuda:0
10 cuda:0
11 cuda:0
12 cuda:0
13 cuda:0
14 cuda:0
15 cuda:0
16 cuda:0
17 cuda:0
18 cuda:0
19 cuda:0
20 cuda:0
21 cuda:0
22 cuda:0
23 cuda:0
24 cuda:0
25 cuda:0
26 cuda:0
27 cuda:0
28 cuda:0
29 cuda:0
30 cuda:0
31 cuda:0
32 cuda:0
33 cuda:0
34 cuda:0
35 cuda:0
36 cuda:0
37 cuda:0
38 cuda:0
39 cuda:0
40 cuda:0
41 cuda:0
42 cuda:0
43 meta
Traceback (most recent call last):
  File "example.py", line 18, in <module>
    print(llama.generate(["Chat:\nHuman: Hi i am an human\nAI:"], stop_ids=[13]))
  File "/home/zhogu/zxrepo/fb-llama/vanilla-llama/inference.py", line 52, in generate
    results, stats = self.generator.generate(
  File "/home/zhogu/zxrepo/fb-llama/vanilla-llama/llama/generation.py", line 74, in generate
    logits = self.model.forward(tokens[:, prev_pos:cur_pos], prev_pos)
  File "/home/zhogu/zxrepo/fb-llama/llama-webapp/myenv/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/zhogu/zxrepo/fb-llama/llama-webapp/myenv/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/zhogu/zxrepo/fb-llama/vanilla-llama/llama/model.py", line 251, in forward
    h = layer(h, start_pos, freqs_cis, mask)
  File "/home/zhogu/zxrepo/fb-llama/llama-webapp/myenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhogu/zxrepo/fb-llama/llama-webapp/myenv/lib/python3.8/site-packages/accelerate/hooks.py", line 160, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
  File "/home/zhogu/zxrepo/fb-llama/llama-webapp/myenv/lib/python3.8/site-packages/accelerate/hooks.py", line 275, in pre_forward
    return send_to_device(args, self.execution_device), send_to_device(kwargs, self.execution_device)
  File "/home/zhogu/zxrepo/fb-llama/llama-webapp/myenv/lib/python3.8/site-packages/accelerate/utils/operations.py", line 133, in send_to_device
    return recursively_apply(_send_to_device, tensor, device, non_blocking, test_type=_has_to_method)
  File "/home/zhogu/zxrepo/fb-llama/llama-webapp/myenv/lib/python3.8/site-packages/accelerate/utils/operations.py", line 82, in recursively_apply
    return honor_type(
  File "/home/zhogu/zxrepo/fb-llama/llama-webapp/myenv/lib/python3.8/site-packages/accelerate/utils/operations.py", line 53, in honor_type
    return type(obj)(generator)
  File "/home/zhogu/zxrepo/fb-llama/llama-webapp/myenv/lib/python3.8/site-packages/accelerate/utils/operations.py", line 85, in <genexpr>
    recursively_apply(
  File "/home/zhogu/zxrepo/fb-llama/llama-webapp/myenv/lib/python3.8/site-packages/accelerate/utils/operations.py", line 101, in recursively_apply
    return func(data, *args, **kwargs)
  File "/home/zhogu/zxrepo/fb-llama/llama-webapp/myenv/lib/python3.8/site-packages/accelerate/utils/operations.py", line 126, in _send_to_device
    return t.to(device, non_blocking=non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!
```

**Comment by zhogu** [comment]
> @lc222 that code is for the huggingface transformers version of llama. I am closing this issue since it is a problem of accelerate in wsl

Thanks, I tried the huggingface transformers version of llama (transformers' [convert script](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/convert_llama_weights_to_hf.py)). It works well when loading 65B model in fp16 on one A100-80G + 140G mem (I also set `device_map` as `auto`). It seems that `accelerator` did not adapt the vanilla torch model of llama-65b.
